### ISSUE TITLE
Reader View fails at New York Times

### ISSUE THREAD

**Issue by howardm** [PalmerAL/min#42]
I'm logged-in to my NYT account.

When clicking Reader View for an article, it produces a page that asks for login information:

https://www.dropbox.com/s/ndpi63a7ob5vrva/NYTError.png?dl=0

Howard

**Comment by PalmerAL** [comment]
This should be fixed now. The issue was that cookies weren't being sent in the request to get the page for reader view, so nytimes couldn't tell whether you were logged in or not.

**Comment by howardm** [comment]
False (for me).

I downloaded a new version and the problem still exists.

Howard

**Comment by PalmerAL** [comment]
Which version did you download? The 1.1.2 version at https://github.com/PalmerAL/min/releases doesn't include this; you'll have to download and install from the master branch.

If you have the right version, and it still isn't working, can you please open the console, and paste the contents of that here?

**Comment by howardm** [comment]
Can you provide me a link to the latest binary ?

Howard

**Comment by PalmerAL** [comment]
Github won't let me upload a file that large in this issue, but there will be a 1.2.0 release in ~1.5 weeks, and the fix will be included with that.

**Comment by PalmerAL** [comment]
1.2.0 has been released; can you please download it from https://github.com/PalmerAL/min/releases and confirm that this is fixed?

**Comment by howardm** [comment]
Great! It works well. Thanks.
